---
- name: Remove old deployment
  command: docker stack rm mystack

- name: Wait for all services to shut down
  pause:
    seconds: 5

- name: Copy config files to remote
  copy:
    src: "{{ item }}"
    dest: "/root/{{ item }}"
  with_items:
    - dashboard.json
    - dashboards.yml
    - logstash.conf
    - stack.yml
    - influx.yml

- name: Set sysctl option for Elasticsearch
  sysctl:
    name: vm.max_map_count
    value: 262144
    reload: yes

- name: Remove old configs
  command: "docker config rm {{ item }}"
  with_items:
    - dashboard.json
    - dashboards.yml
    - logstash.conf
    - influx.yml
  ignore_errors: yes

- name: Set up new Docker configs
  command: "docker config create {{ item }} ./{{ item }}"
  args:
    chdir: /root
  with_items:
    - dashboard.json
    - dashboards.yml
    - influx.yml
    - logstash.conf

- name: Redeploy stack
  command: docker stack deploy -c stack.yml mystack
  args:
    chdir: /root

