version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.2
    environment:
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    ports:
      - '8000:5601'
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  influx:
    image: influxdb
    volumes:
      - influx_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: cadvisor
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:master
    ports:
      - "8002:3000"
    environment:
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_DASHBOARDS_JSON_PATH: /dashboards
    configs:
      - source: dashboard.json
        target: /dashboards/dashboard.json
        mode: 0777
        uid: '104'
        gid: '107'
      - source: dashboards.yml
        target: /usr/share/grafana/conf/provisioning/dashboards/dashboards.yml
        mode: 0777
        uid: '104'
        gid: '107'
      - source: influx.yml
        target: /usr/share/grafana/conf/provisioning/datasources/influx.yml
        mode: 0777
        uid: '104'
        gid: '107'

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.Hostname}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  primenumbers:
    image: kelog/primenumbers:latest
    ports:
      - 8080:8080
    deploy:
      replicas: 10
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role != manager

configs:
  logstash.conf:
    external: true
  dashboard.json:
    external: true
  dashboards.yml:
    external: true
  influx.yml:
    external: true

volumes:
  influx_data:
  esdata:
